
<li class="fields"><?php echo $this->getLayout()->createBlock('customer/widget_name')->setTemplate('mw_onestepcheckout/name.phtml')->setObject($this->getAddress())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?></li>
<li class="fields">
	<div class="field">
				<?php if(!$this->isCustomerLoggedIn()): ?>
							<div class="field">
			<label for="billing:email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
			<div class="input-box">
				<input type="text" name="billing[email]" id="billing:email"
					value="<?php echo $this->htmlEscape($this->getAddress()->getEmail()) ?>"
					title="<?php echo $this->__('Email Address') ?>"
					class="input-text inputtext validate-email required-entry" />
			</div>
		</div>
				<?php endif ?>
	</div>
</li>
<li class="fields">
	<div class="field">
		<label for="billing:region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
		<div class="input-box">
			<select id="billing:region_id" name="billing[region_id]"
				title="<?php echo $this->__('State/Province') ?>"
				class="validate-select" style="display: none;">
				<option value=""><?php echo $this->__('Please select region, state or province') ?></option>
			</select>
			<script type="text/javascript">
									//<![CDATA[
										$('billing:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
									//]]>
									</script>
			<input type="text" id="billing:region" name="billing[region]"
				value="<?php echo $this->htmlEscape($this->getAddress()->getRegion()) ?>"
				title="<?php echo $this->__('State/Province') ?>"
				class="input-text inputtext" style="display: none;" />
		</div>
	</div>

	<div class="field">
		<label for="billing:city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
		<div class="input-box">
			<select id="billing:city_id" name="billing[city_id]"
				title="<?php echo $this->__('City') ?>" class="validate-select"
				style="display: none;">
				<option value=""><?php echo $this->__('请选择市') ?></option>
			</select>
			<script type="text/javascript">
                        //<![CDATA[
                            $('billing:city_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getCityId() ?>");
                        //]]>
                        </script>
			<input type="text" title="<?php echo $this->__('City') ?>"
				name="billing[city]"
				value="<?php echo $this->htmlEscape($this->getAddress()->getCity()) ?>"
				class="input-text inputtext required-entry" id="billing:city" />
		</div>
	</div>


	<div class="field">
		<label for="billing:bdistrict_id" class="required"><?php echo $this->__('县') ?></label>
		<div class="input-box">
			<select id="billing:district_id" name="billing[district_id]"
				title="<?php echo $this->__('县') ?>" class="validate-select"
				style="display: none; width: 230px;">
				<option value=""><?php echo $this->__('请选择县') ?></option>
			</select>
			<script type="text/javascript">
                        //<![CDATA[
                            $('billing:district_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getDistrictId() ?>");
                        //]]>
                        </script>
			<input type="text" id="billing:district" name="billing:district"
				value="<?php echo $this->escapeHtml($this->getAddress()->getdistrict()) ?>"
				title="<?php echo $this->__('县') ?>"
				class="input-text required-entry />
		</div>
	</div>
</li>

<li class="fields">
	<div class="field">
		<label for="billing:street1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
		<div class="input-box">
			<input type="text" title="<?php echo $this->__('Street Address') ?>"
				name="billing[street][]" id="billing:street1"
				value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(1)) ?>"
				class="input-text inputtext required-entry" />
		</div>

	</div>

	<div class="field" style="display: none;">
		<?php for ($_i=2, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++): ?>
	<div class="input-box">
			<input type="text"
				title="<?php echo $this->__('Street Address %s', $_i) ?>"
				name="billing[street][]" id="billing:street<?php echo $_i?>"
				value="<?php echo $this->htmlEscape($this->getAddress()->getStreet($_i)) ?>"
				class="input-text inputtext" />
		</div>
<?php endfor ?>
	</div>
</li>
<li class="fields">
	<div class="field">
		<label for="billing:telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
		<div class="input-box">
			<input type="text" name="billing[telephone]"
				value="<?php echo $this->htmlEscape($this->getAddress()->getTelephone()) ?>"
				title="<?php echo $this->__('Telephone') ?>"
				class="input-text inputtext required-entry" id="billing:telephone" />
		</div>
	</div>

	<div class="field">
		<label for="billing:company" class="required"><?php echo $this->__('Company') ?></label>
		<div class="input-box">
			<input type="text" id="billing:company" name="billing[company]"
				value="<?php echo $this->htmlEscape($this->getAddress()->getCompany()) ?>"
				title="<?php echo $this->__('Company') ?>"
				class="input-text inputtext" />
		</div>
	</div>
</li>

<li class="fields">
	<div class="field">
		<label for="billing:postcode" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
		<div class="input-box">
			<input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>"
				name="billing[postcode]" id="billing:postcode"
				value="<?php echo $this->htmlEscape($this->getAddress()->getPostcode()) ?>"
				class="input-text inputtext required-entry" />
		</div>
	</div>
	<div class="field">
		<label for="billing:fax" class="required"><?php echo $this->__('Fax') ?></label>
		<div class="input-box">
			<input type="text" name="billing[fax]"
				value="<?php echo $this->htmlEscape($this->getAddress()->getFax()) ?>"
				title="<?php echo $this->__('Fax') ?>" class="input-text inputtext"
				id="billing:fax" />
		</div>
	</div>
	
	<div class="field" style="display: none;">
		<label for="billing:country_id" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
		<div class="input-box">
			<select name="country_id" id="country"
				class="validate-select jqtransformdone" title="国家"><option value="">
				</option>
				<option value="CN" selected="selected">$this->__('中国')</option></select>
		</div>
	</div>
</li>
<script>
	$MW_Onestepcheckout(function(){
			$MW_Onestepcheckout("#billing\\:street1").css('width','245px');
			$MW_Onestepcheckout("#billing\\:street2").css('width','245px');
	});
</script>

<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    var shippingRegionUpdater = new RegionUpdater('country', 'billing:region', 'billing:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
    var shippingCityUpdater = new RegionUpdater('billing:region_id', 'billing:city', 'billing:city_id', <?php echo $this->helper('directoryex')->getCityJson() ?>, undefined, 'postcode');
	var shippingDistrictUpdater = new RegionUpdater('billing:city_id', 'billing:district', 'billing:district_id', <?php echo $this->helper('directoryex')->getDistrictJson() ?>, undefined, 'postcode');
	shippingRegionUpdater.setChildUpdater(shippingCityUpdater);
	shippingCityUpdater.setChildUpdater(shippingDistrictUpdater); 
//]]>
</script>
