<?php if(Mage::getStoreConfig('onestepcheckout/config/enabled')):?>
	
<script type="text/javascript">
var message_payment = "<?php echo Mage::helper('onestepcheckout')->__('Please select a payment method for your order!');?>";//giup dua cac' chuoi~ nay` vao file .csv
var message_ship = "<?php echo Mage::helper('onestepcheckout')->__('Please select a shipping method for your order!');?>";
function updateShippingMethod()
{
	urls= '<?php echo Mage::getUrl('onestepcheckout/index/updateshippingmethod') ?>';


	$MW_Onestepcheckout('#message-box').html('');
	$MW_Onestepcheckout('.btn-checkout').attr('disabled','disabled');
	$MW_Onestepcheckout('#loading-mask').css('display','block');
	$MW_Onestepcheckout.ajax({
	   type: "POST",
	   url: urls,
	   data: "shipping_method="+$MW_Onestepcheckout('input[name=shipping_method]:checked').val(),
	   success: function(msg){

		 
		$MW_Onestepcheckout('#checkout-review-load').html(msg);
		$MW_Onestepcheckout('#loading-mask').css('display','none');
		$MW_Onestepcheckout('.btn-checkout').removeAttr('disabled');
	   }
	});
}
function updatePaymentMethod(value)
{
	//msg = "Loadding ...";
	//$MW_Onestepcheckout('#checkout-review-load').html(msg);	// #checkout-review-load: id cua? bang? tong? tie`n, lenh .html(msg) cho phep gi lai. noi dung cua id voi'noi dung chua' trong bien $msg
	$MW_Onestepcheckout('#message-box').html('');
	$MW_Onestepcheckout('#loading-mask').css('display','block');
	$MW_Onestepcheckout('.btn-checkout').attr('disabled','disabled');
	$MW_Onestepcheckout.ajax({
	   type: "POST",
	   url: "<?php echo Mage::getUrl('onestepcheckout/index/updatepaymentmethod')?>",
	   data: "payment%5Bmethod%5D="+value,
	   success: function(msg){
		if(msg.search("<script")!=0){
		//alert(msg.search("<script"));
		$MW_Onestepcheckout('#checkout-review-load').html(msg);
		}
		//else
		//	$MW_Onestepcheckout('#checkout-review-load').append(msg);	//message thong bao info payment method ko hop le
		$MW_Onestepcheckout('#loading-mask').css('display','none');
		$MW_Onestepcheckout('.btn-checkout').removeAttr('disabled');
	   }
	 });
}
function updateCoupon(code,isremove){
	$MW_Onestepcheckout('#message-box').html('');
	$MW_Onestepcheckout('#loading-mask').css('display','block');
	$MW_Onestepcheckout('.btn-checkout').attr('disabled','disabled');
	$MW_Onestepcheckout.ajax({
	   type: "POST",
	   url: "<?php echo Mage::getUrl('onestepcheckout/index/updatecoupon')?>",
	   data: "coupon_code="+code+"&remove="+isremove,
	   success: function(msg){
		str=jQuery.parseJSON(msg);
		//console.debug(str.coupon);
		//console.debug(str.view);
		$MW_Onestepcheckout('#tab-coupon').html(str.coupon);
		$MW_Onestepcheckout('#checkout-review-load').html(str.view);
		$MW_Onestepcheckout('#loading-mask').css('display','none');
		$MW_Onestepcheckout('.btn-checkout').removeAttr('disabled');
	   }
	});	
}
function updateQtyProduct(){
	qtydata=$MW_Onestepcheckout("input[name^='cart\[']"); //selector all element have name ~ cart[
	//console.debug(qtydata.length);
	str='';
	for(var i=0;i< qtydata.length;i++){
		//console.debug(qtydata[i]);
		str_escape=escape(qtydata[i].name)+"="+qtydata[i].value;
		str+=str_escape;
		if(i!=qtydata.length-1){str+="&"}
	}
	//str_escape=escape(str);
	//console.debug(str_escape);
	$MW_Onestepcheckout('#message-box').html('');
	$MW_Onestepcheckout('#loading-mask').css('display','block');
	$MW_Onestepcheckout('.btn-checkout').attr('disabled','disabled');
	$MW_Onestepcheckout.ajax({
	   type: "POST",
	   url: "<?php echo Mage::getUrl('onestepcheckout/index/updateqty')?>",
	   data: str,
	   success: function(msg){
		str=jQuery.parseJSON(msg);

		if(str.view.search("<script")!=0){
		//alert(msg.search("<script"));
		$MW_Onestepcheckout('#checkout-review-load').html(str.view);
		}
		else
			$MW_Onestepcheckout('#checkout-review-load').append(str.view);
		$MW_Onestepcheckout('#loading-mask').css('display','none');
		$MW_Onestepcheckout('.btn-checkout').removeAttr('disabled');
	   }
	});		
}
function removeProduct(id){
	//kiem tra xem co block gift message
	hasgift=(typeof($MW_Onestepcheckout('#allow-gift-message-container'))!='undefined')?1:0;
	//alert(typeof($MW_Onestepcheckout('#allow-gift-message-container')));
	//console.debug($hasgift);
	$MW_Onestepcheckout('#message-box').html('');
	$MW_Onestepcheckout('#loading-mask').css('display','block');
	$MW_Onestepcheckout('.btn-checkout').attr('disabled','disabled');
	$MW_Onestepcheckout.ajax({
	   type: "POST",
	   url: "<?php echo Mage::getUrl('onestepcheckout/index/removeproduct')?>",
	   data: "id="+id+'&hasgiftbox='+hasgift,
	   success: function(msg){
		str=jQuery.parseJSON(msg);

		if(str.view.search("<script")!=0){
		//alert(msg.search("<script"));
			if(str.giftbox){
				$MW_Onestepcheckout('#checkout-review-load').html(str.view);
				$MW_Onestepcheckout('#onepage-checkout-shipping-method-additional-load').html(str.giftbox);
			}else{
				$MW_Onestepcheckout('#checkout-review-load').html(str.view);
			}
		}
		else{
			$MW_Onestepcheckout('#checkout-review-load').append(str.view);			
		}
		$MW_Onestepcheckout('#loading-mask').css('display','none');
		$MW_Onestepcheckout('.btn-checkout').removeAttr('disabled');
	   }
	});	
}
$MW_Onestepcheckout(function(){
	
		$MW_Onestepcheckout("#loginbox").fancybox({
			'titlePosition'		: 'inside',
			'transitionIn'		: 'none',
			'transitionOut'		: 'none'
		});
		$MW_Onestepcheckout("#onestepcheckout-toc-link").fancybox({
			'titlePosition'		: 'inside',
			'transitionIn'		: 'none',
			'transitionOut'		: 'none'
		});
		$MW_Onestepcheckout("#forgotpassword").fancybox({
			'titlePosition'		: 'inside',
			'transitionIn'		: 'none',
			'transitionOut'		: 'none'
		});
		$MW_Onestepcheckout("#backlogin").fancybox({
			'titlePosition'		: 'inside',
			'transitionIn'		: 'none',
			'transitionOut'		: 'none'
		});	
	<?php
		$countryid="";
		$islogin=0;
		if(Mage::getSingleton('customer/session')->isLoggedIn()){
			$islogin=1;
			
			if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling())		//lay thong tin customer login va` co address default
			$countryid=Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)->getData('country_id');
			$currentCustomer = Mage::getSingleton('customer/session')->getCustomer();
			$addresses = $currentCustomer->getAddresses();
			$has_address= count($addresses);
		}

	?>
	var str_value=",,,,,";
	<?php if($islogin AND $has_address):?>
		str_value="<?php echo $countryid;?>";
	<?php endif;?>
	if($MW_Onestepcheckout("#billing\\:country_id option:selected").val()){		//neu tag select billing:country co 1 gia tri duoc select
		str_value=","+$MW_Onestepcheckout("#billing\\:country_id option:selected").val()+",,,,";	//gan gia tri
	}
	var completeajax=1;
	$MW_Onestepcheckout('.btn-checkout').attr('disabled','disabled');
	$MW_Onestepcheckout.ajax({
	   type: "POST",
	   url:"<?php echo Mage::getUrl('onestepcheckout/index/updateshippingmethod')?>",
	   data: "shipping_method="+$MW_Onestepcheckout('input[name=shipping_method]:checked').val(),
	   success: function(msg){
		
		$MW_Onestepcheckout('#checkout-review-load').html(msg);
		
	   }
	});
	if($MW_Onestepcheckout("input[name=payment\[method\]]:checked").val() && payment_load()){
		value=$MW_Onestepcheckout("input[name=payment\[method\]]:checked").val();
		$MW_Onestepcheckout.ajax({
		   type: "POST",
		   url: "<?php echo Mage::getUrl('onestepcheckout/index/updatepaymentmethod')?>",
		   data: "payment%5Bmethod%5D="+value,
		   success: function(msg){
			   
			if(msg.search("<script")!=0){
			$MW_Onestepcheckout('#checkout-review-load').html(msg);
			}
			else
				$MW_Onestepcheckout('#checkout-review-load').append(msg);
		   }
		 });
	}
	$MW_Onestepcheckout('.btn-checkout').removeAttr('disabled');
		$MW_Onestepcheckout('.btn-checkout').click(function(e){
					var form = new VarienForm('onestep_form');
					var logic=true;
					<?php if(Mage::helper('onestepcheckout')->onlyProductDownloadable()):?>
							var notshipmethod=1;
					<?php else:?>
							var notshipmethod=$MW_Onestepcheckout("input[name=shipping_method]:checked").val();
					<?php endif?>
					var notshipmethod = 1;
					if(!$MW_Onestepcheckout("input[name=payment[method]]:checked").val() || !notshipmethod){
						logic=false;
					}
					if(!$MW_Onestepcheckout("input[name=payment[method]]:checked").val()){	//neu cac method payment chua duoc chon
						if(!$MW_Onestepcheckout('#advice-required-entry_payment').length){	//neu' phan tu valid chua duoc hien len, thi` cho no hien len
						$MW_Onestepcheckout('#checkout-payment-method-load').append('<dt><div class="validation-advice" id="advice-required-entry_payment" style="">'+message_payment+'</div></dt>');
						}
					}
					else
					$MW_Onestepcheckout('#advice-required-entry_payment').remove();
					if(!notshipmethod){
						if(!$MW_Onestepcheckout('#advice-required-entry_shipping').length){
						$MW_Onestepcheckout('#checkout-shipping-method-loadding').append('<dt><div class="validation-advice" id="advice-required-entry_shipping" style="">'+message_ship+'</div></dt>');
						}

					}
					else
						$MW_Onestepcheckout('#advice-required-entry_shipping').remove();
					if(!form.validator.validate())	{
						val=$MW_Onestepcheckout('#billing\\:email').val();
						emailvalidated=Validation.get('IsEmpty').test(val) || /^([a-z0-9,!\#\$%&'\*\+\/=\?\^_`\{\|\}~-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z0-9,!\#\$%&'\*\+\/=\?\^_`\{\|\}~-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*@([a-z0-9-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z0-9-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*\.(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]){2,})$/i.test(val);
						if(val!="" && emailvalidated){
							updateEmailmsg(val);
						}
						Event.stop(e);				
					}
					else{
						if(logined()!=1){
							val=$MW_Onestepcheckout('#billing\\:email').val();
							emailvalidated=Validation.get('IsEmpty').test(val) || /^([a-z0-9,!\#\$%&'\*\+\/=\?\^_`\{\|\}~-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z0-9,!\#\$%&'\*\+\/=\?\^_`\{\|\}~-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*@([a-z0-9-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z0-9-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*\.(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]){2,})$/i.test(val);
							if(val!="" && emailvalidated){
								msgerror=updateEmailmsg(val);
							}
							if(msgerror==0){
								return false;
							}
						}
						if(logic){
						$MW_Onestepcheckout('#onestep_form').submit();
						$MW_Onestepcheckout('.btn-checkout').attr("disabled","disabled");
						}
						else {
							return false;
						}
					}
					return false;
		});
});
</script>
<?php

?>
	<hidden value="Welcome to One Step Checkout Pro"></hidden>
	<hidden value="Please enter your details below to complete your purchase."></hidden>
	<!--  <h1><?php echo $this->__(Mage::getStoreConfig('onestepcheckout/config/page_title'))?></h1>
	<p><?php echo $this->__(Mage::getStoreConfig('onestepcheckout/config/page_content'))?></p>-->
	<div id="message-box">
		<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
	</div>
	<?php	if(!$islogin):?>
		<?php if(Mage::getStoreConfig('onestepcheckout/config/enable_quicklogin')):?>
		<strong><a  href="<?php echo $this->getUrl('customer/account/login')?>" title=""><span style="font-size: 15px;"><?php echo $this->__('Already registered? Click here to login.');?></span></a></strong>
		<?php endif?>
	<?php endif?>

	<div class="onestepcheckout-threecolumns checkoutcontainer onestepcheckout-skin-generic">
		<form id="onestep_form" action="<?php echo $this->getUrl('onestepcheckout/index/updateordermethod') ?>" method="POST">

			<div class="onestepcheckout-column-left">	
				<p class="onestepcheckout-numbers onestepcheckout-numbers-1"><?php echo $this->__('Billing address');?></p>
				<div>
				<?php echo $this->getChildHtml('billing');?>
				</div>
				<br>
			<?php if(!Mage::helper('onestepcheckout')->onlyProductDownloadable()):?>
			<?php if(Mage::getStoreConfig('onestepcheckout/config/allowshippingotheraddress')):?> 
				<div style="display:none;" id="shipping_show">
				<p class="onestepcheckout-numbers"><?php echo $this->__('Shipping address');?></p>
				<?php echo $this->getChildHtml('shipping');?>
				</div>
			<?php endif;?>
			<?php endif;?>
			</div>
			<div class="onestepcheckout-column-2">
				<div id="onestepcheckout-column-container">
				<?php if(!Mage::helper('onestepcheckout')->onlyProductDownloadable()):?>
					<div class="onestepcheckout-column-middle">	
						<p class="onestepcheckout-numbers onestepcheckout-numbers-2"><?php echo $this->__('Shipping method');?></p>
						<div>
						<?php echo $this->getChildHtml('shipping_method');?>
						</div>
					</div>
				<?php endif?>
					<div class="onestepcheckout-column-right">
						<p class="onestepcheckout-numbers onestepcheckout-numbers-3"><?php echo $this->__('Payment method');?></p>
						<div>
						<?php echo $this->getChildHtml('payment');?>
						</div>
					</div>
					<div class="clear_both">&nbsp;</div>
				</div>
				<div class="review">
						<p class="onestepcheckout-numbers onestepcheckout-numbers-4"><?php echo $this->__('Review your order');?></p>
						<div>
						<?php echo $this->getChildHtml('review');?>
						</div>	
				</div>
			</div>
			<div class="clear_both">&nbsp;</div>			
		</form>
		<?php if(version_compare(Mage::getVersion(),'1.5.0.1','>='))://fix cho magento 1.3?>
				<div style="display: none;">
					<div id="inline1" style="width:400px;height:235px;overflow:auto;">
						<?php echo $this->getChildHtml('login');?>	
					</div>
					<div id="inline3" style="width:440px;height:190px;overflow:auto;">
						<?php echo $this->getChildHtml('forgotpassword');?>	
					</div>
					<div id="inline2" style="width:<?php echo Mage::getStoreConfig('onestepcheckout/termcondition/boxwidth')?>;height:<?php echo Mage::getStoreConfig('onestepcheckout/termcondition/boxheight')?>;overflow:auto;">
						<h1><?php echo $this->__('Terms and Conditions');?> </h1>
						<br>
						<?php echo $this->__(Mage::getStoreConfig('onestepcheckout/termcondition/content_options'));?>
					</div>
				</div>	
		<?php else:?>
				<div style="display: none;">
					<div id="inline1" style="width:435px;height:240px;overflow:auto;">
						<?php echo $this->getChildHtml('login');?>	
					</div>
					<div id="inline3" style="width:445px;height:205px;overflow:auto;">
						<?php echo $this->getChildHtml('forgotpassword');?>	
					</div>
					<div id="inline2" style="width:<?php echo Mage::getStoreConfig('onestepcheckout/termcondition/boxwidth')?>;height:<?php echo Mage::getStoreConfig('onestepcheckout/termcondition/boxheight')?>;overflow:auto;">
						<h1><?php echo $this->__('Terms and Conditions');?> </h1>
						<br>
						<?php echo $this->__(Mage::getStoreConfig('onestepcheckout/termcondition/content_options'));?>
					</div>
				</div>	
		<?php endif;?>
		</div>
	<div class="clear_both">&nbsp;</div>
<div style="left: -2px; width: 1200px; min-height: 710px; display: none;top:51%;" id="loading-mask">
    <p id="loading_mask_loader" class="loader"><img alt="Loading..." src="<?php echo $this->getSkinUrl('mw_onestepcheckout/images/ajax-loader-tr.gif')?>"><br>Please wait...</p>
</div>
<?php endif?>