<div>
	<!-- Add jQuery library -->
	<script type="text/javascript" src="/js/fb/jquery-1.10.1.min.js"></script>
	<script type="text/javascript">
		jQuery.noConflict();
	</script>

	<!-- Add mousewheel plugin (this is optional) -->
	<script type="text/javascript" src="/js/fb/jquery.mousewheel-3.0.6.pack.js"></script>

	<!-- Add fancyBox main JS and CSS files -->
	<script type="text/javascript" src="/source/jquery.fancybox.js?v=2.1.5"></script>
	<link rel="stylesheet" type="text/css" href="/source/jquery.fancybox.css?v=2.1.5" media="screen" />

	<script type="text/javascript">
		jQuery(document).ready(function() {
			/*
			 *  Simple image gallery. Uses default settings
			 */

			jQuery('.fancybox').fancybox();

			jQuery(".fancybox-manual-album").click(function() {
				jQuery.fancybox.open({
					href : '/source/flipbook.html',
					type : 'iframe',
					padding : 2,
					width :	'1600px',
					height : '1200px'
				});
			});

		});


	</script>
	<style type="text/css">
		.fancybox-custom .fancybox-skin {
			box-shadow: 0 0 50px #222;
		}
	</style>
	<ul>
		<li><a class="button fancybox-manual-album fancybox-manual-album.iframe" href="#"><?php echo $this->__("Album preview");?></a></li>
	</ul>
</div>
