<div>
	<!-- Add jQuery library -->
	<script type="text/javascript" src="/js/fb/jquery-1.10.1.min.js"></script>

	<!-- Add mousewheel plugin (this is optional) -->
	<script type="text/javascript" src="/js/fb/jquery.mousewheel-3.0.6.pack.js"></script>

	<!-- Add fancyBox main JS and CSS files -->
	<script type="text/javascript" src="/source/jquery.fancybox.js?v=2.1.5"></script>
	<link rel="stylesheet" type="text/css" href="/source/jquery.fancybox.css?v=2.1.5" media="screen" />

	<!-- Add Button helper (this is optional) 
	<link rel="stylesheet" type="text/css" href="source/helpers/jquery.fancybox-buttons.css?v=1.0.5" />
	<script type="text/javascript" src="source/helpers/jquery.fancybox-buttons.js?v=1.0.5"></script>
-->
	<!-- Add Thumbnail helper (this is optional) 
	<link rel="stylesheet" type="text/css" href="source/helpers/jquery.fancybox-thumbs.css?v=1.0.7" />
	<script type="text/javascript" src="source/helpers/jquery.fancybox-thumbs.js?v=1.0.7"></script>
-->
	<!-- Add Media helper (this is optional) 
	<script type="text/javascript" src="source/helpers/jquery.fancybox-media.js?v=1.0.6"></script>
-->
	<script type="text/javascript">
		$(document).ready(function() {
			/*
			 *  Simple image gallery. Uses default settings
			 */

			$('.fancybox').fancybox();

			$(".fancybox-manual-album").click(function() {
				$.fancybox.open({
					href : '/source/flipbook.html',
					type : 'iframe',
					padding : 2,
					width :	'1600px',
					height : '1200px'
				});
			});


			//$(".fancybox-overlay-fixed").click(function(){alert("in index");});
		});


	</script>
	<style type="text/css">
		.fancybox-custom .fancybox-skin {
			box-shadow: 0 0 50px #222;
		}
	</style>
	<ul>
		<li><a class="button fancybox-manual-album fancybox-manual-album.iframe" href="#"><?php echo $this->__("Album preview");?></a></li>
	</ul>
	<!--
	<button class="button fancybox-manual-album fancybox-manual-album.iframe" href="#">Album preview</button>
	-->
</div>
